[package]
name = "im-robot"
version = "1.1.13"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "im_robot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "macos-private-api", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = "3"
reqwest = { version = "0.13", default-features = false, features = ["charset", "http2", "json", "native-tls", "stream", "system-proxy"] }
tauri-plugin-notification = "^2"
tauri-plugin-autostart = "^2"
screenshots = "0.8.10"
base64 = "0.22"
tauri-plugin-dialog = "^2"
rusqlite = { version = "0.37", features = ["bundled"] }
chrono = "0.4"
wasmtime = "45"
wasmtime-wasi = "45"
rdev = "0.5.3"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = "0.3"
core-graphics = "0.23"
objc2-foundation = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
